language: python
os:
  - linux
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install: 
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov codecov pytest  
install:
  - pip install -r requirements.txt
  - pip install pylint scikit-learn==0.23.2 ipython 
script:
  - pytest -s tests --cov=codecov

env:
- CODECOV_TOKEN='6f003a89-f2c5-4586-845f-79c0e5410aa5'

after_success:
  - codecov # submit coverage 
  - bash <(curl -s https://codecov.io/bash)
  



