language: python
os:
  - linux
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install: 
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov codecov 
install:
 # - python setup.py develop
 # - pip install -e ".[tests]" . # install package + test dependencies
  - pip install -r requirements.txt
  - pip install pylint scikit-learn==0.23.2 ipython 
script:
  - pytest -s tests --cov=codecov
after_success:
  - codecov # submit coverage 
  - bash <(curl -s https://codecov.io/bash)
  
#deploy:
#  provider: testpypi
#  user: "__token__"
#  password:
#    secure: iVB34uR2CL/Hn+lXEcipt4sGK5a8hZEfW8o0DeEZHh6NPO+ykkOjUfavlGBGFj2YBHXHobeNDgNF63+g37oxaIz8UOvp6MZtcuxzNUBuYvzkOSkOevQFttLJCQuVoa1dgfOur0zi2Q0U0xJzqNPoUEeL3x15yM+WXrB0+blYaBKt9y2VqMztlJExMGzZS6N4cccm8YdGSkt6dKovVvzR6ShTT/dIVmeuaVzVkJ6NLS7aw8i71I7zxxF7+K86tlWm8+L/LteyJyLhENVO614el6RxYFoKrLwYthIqnLMwxpZktVejymkW1BhaZvjIUwq7nqGGm9CklZpbDWNs2VP+UUmC1ziYuA/D/zPQy8GI712aZguTlF0gJa1diqLkzDwNIBcPV2xYlbipbkAExzgZnm7yKs9x3wRKDw2GJsYHeE1NvNJR8SN7MeUbICmekHHzQ6yr9B0ZfjHNjLmBKaFavwB8jEHj0u/2PBmtgLL8j2kL8hXoI/jPnihbUQ4nog/WkGQCCOh940zhq5AtZrwxxDmwl2zSwAJiICri6ah10c+1As1kncps4ip23d7WbxcFfYpRb+kn8NS9X9NX1D6c1cFggt96zPVkQ3BAW4vHaXCKxqKw8fZ0cDYK3A6IKdzSauLiTv8bVl7wI/1yATBkjsIjT00p5zg8jvl8jK+BQ8o=
#  on:
#    tags: true
#  distributions: "sdist" # bdist_wheel breaks because pipy rejects linux wheels
#  skip_cleanup: true
#  skip_existing: true



